name: CI-CD

on: [push] #to any branch
  # Triggers the workflow on push or pull request events but only for the Develop branch
  #push:
  #  branches: [ Develop ]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains multiple jobs

  deploy_to_dev:
      # The type of runner that the job will run on

      runs-on: ubuntu-latest

#Deploy dev-test      
      if: github.ref == 'refs/heads/back-develop.neumapp.site' # run this job only for the dev branch
      steps:
         - name: Hello world
           run: |
               echo "Hi!"
        #Back
         - name: checkout repo
           uses: actions/checkout@v2

         - name: Create SSH key
           run: |
               install -m 600 -D /dev/null ~/.ssh/id_rsa
               echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
               ssh-keyscan neumapp.site > ~/.ssh/known_hosts          
        
         - name: Deploy Back
           run: |
               rsync -ra --delete ./ ubuntu@neumapp.site:/home/ubuntu/neumapp/dev/s14-35-n-node-react/
               ssh -f ubuntu@${{ secrets.SSH_HOST }} /home/ubuntu/neumapp/dev/dev.sh
#Deploy qa-test      
      if: github.ref == 'refs/heads/back-qa.neumapp.site' # run this job only for the dev branch
      steps:
         - name: Hello world
           run: |
               echo "Hi!"
        #Back
         - name: checkout repo
           uses: actions/checkout@v2

         - name: Create SSH key
           run: |
               install -m 600 -D /dev/null ~/.ssh/id_rsa
               echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
               ssh-keyscan neumapp.site > ~/.ssh/known_hosts          
        
         - name: Deploy Back
           run: |
               rsync -ra --delete ./ ubuntu@neumapp.site:/home/ubuntu/neumapp/qa/s14-35-n-node-react/
               ssh -f ubuntu@${{ secrets.SSH_HOST }} /home/ubuntu/neumapp/qa/qa.sh
